### ISSUE TITLE
If a song is not found on Spotify, it is mapped to a "closest" one

### ISSUE THREAD

**Issue by cheets** [leeroybrun/chrome-shazify#12]
For example artist "Years & Years"'s song "King" is not yet on spotify (http://en.wikipedia.org/wiki/Years_%26_Years). This Shazam tag is currently mapped to artist "Ten Years After"'s song "King of the blues". Here's the log entry:

```
[info] Mon Feb 02 2015 11:08:37 GMT+0200 (EET) - [Spotify] Searching for track "track:King artist:Years+&+Years"...
[info] Mon Feb 02 2015 11:08:37 GMT+0200 (EET) - [Spotify] Track found "6JzDyGLNeV1u3mm2nii9VM".
```

Since it founds a song there's no way in the extension to alter the search terms or say that this song can't be found in Spotify.

Also once you remove the song from your playlist in Spotify, resyncing the chrome extension doesn't bring it back.

**Comment by leeroybrun** [comment]
You are right, we should have a way to change the track found on Spotify.

If a track is found and added to playlist, we should have actions (icons shown on hover ?) :

- "Change track" : show search form (pre-filled with artist/track from Shazam), click "Search" and display a list of tracks found on Spotify. The user can then click on a track to replace the corresponding track in the playlist.
- "Mark as not found" : if a track is found, but it's not the right one, we should be able to mark it as "not found".

This way, you can even add a song back to a playlist if you manually removed it from Spotify. You just have to click "Change track", search the song again and add.

What do you think about this ?

Unfortunately I don't have the time for now to implement this, but I'll try to do this soon !

**Comment by cheets** [comment]
Yes, sounds good.

I didn't dig enough deep to the source code to see how search results are parsed but it would be better to mark track as not found if we don't get a proper hit. I guess Spotify API always provides some results so we would need to double check that the result has same name for artist and album than what we searched for.

By marking tracks automatically as not found would require user action to fix the search terms or accept that there really is no track available. This would be better UX. If we automatically map to closest, user first needs to find out that some tracks are wrong and then go and try to fix it - bad UX.

**Comment by leeroybrun** [comment]
Yes, nice catch, this is a great idea.

I will try to implement this as soon I can, maybe in the following weeks. I'm quite busy right now.

If you want to take a look at the source code and try to implement this, feel free, I would be happy to merge ! :-)

**Comment by leeroybrun** [comment]
The new version is out! It's uploaded on the Chrome webstore, pending review.

Should fixes the issues discussed here.

Let me know if it's not the case.
Thanks

New version PR : #19
