### ISSUE TITLE
Not Found List

### ISSUE THREAD

**Issue by karlafernandes** [leeroybrun/chrome-shazify#22]
Love your extension!!! It saved me from doing manually from 2011 :) 
I would love to have the possibility to have an easier way to match the not found with the right versions, I saw some really don't exist, but those who have more than a version maybe could be shown one after another and just be possible to click on the version you want? I don't know if I could help, but maybe? :D with instructions hahaha Thanks, great work!!! <3

**Comment by leeroybrun** [comment]
Thanks for the feedback, it's really appreciated! :-)

When a song is not found, or even if it's found, you can click on the icon on the right (either a cross or a check).
Here you can edit the search terms and it shows you the results below.
Then you can select the one you want to be added to the Spotify playlist.

![image](https://user-images.githubusercontent.com/1729528/32433627-eea22ada-c2db-11e7-82f0-53e794e92b84.png)

Is it not what you wanted?

**Comment by karlafernandes** [comment]
Hi Leeroy, I just saw your update now, I am sorry. Yes, I can do that, but sometimes for some reason the song name comes with extra characters and can't be found because of that and I can't search for it and match with the right version, did it explained better my problem? :D thanks again!
