### ISSUE TITLE
Tags not updating

### ISSUE THREAD

**Issue by wavesko** [leeroybrun/chrome-shazify#24]
Hi,
First of all, great app. Been using it for a while now.
But I have a weird issue past couple of days. 
Tag fetching from spotify and shazam is working, but it wont fetch the id of the song from the internet, or offer replacement id. It just stays as "no track found" :/
code from the console included :)

Thanks!

[console.docx](https://github.com/leeroybrun/chrome-shazify/files/2459947/console.docx)

**Comment by leeroybrun** [comment]
Thanks for your report and sorry for the delay.

I just made a fix and pushed the new version (0.4.7) to the Chrome webstore.

As soon as you receive the update, can you let me know if it starts working again on your side?

Thanks!

**Comment by wavesko** [comment]
No problem, thank you for responding.
All good now on this side, as soon as i fired it up.
Again, small and amazing app, thanks for this.

Regards

**Comment by leeroybrun** [comment]
Great!

Thanks a lot for your feedback, it's really appreciated!
Glad it's usefull. :-)

Have a nice day!
