### ISSUE TITLE
App still needed since Shazam's auto update doesn't sync everything

### ISSUE THREAD

**Issue by mrk3767** [leeroybrun/chrome-shazify#26]
The integration between Shazam and Spotify only syncs new songs that you discover. It doesn't copy your full library to a Spotify playlist.

The extension also no longer works with Shazam due to changes to the site.

**Comment by leeroybrun** [comment]
The extension seems to still works fine on my computer.

Can you tell me exactly the error you're getting or what's not working for you?

Thanks
