### ISSUE TITLE
Shazify doesn't want to connect to Shazam after logging to my shazam account

### ISSUE THREAD

**Issue by Tonymelad** [leeroybrun/chrome-shazify#27]
I used the the extension a couple of months ago and it worked fine but now i am trying to update my tags and even though i logged to my Shazam account the shazify doesn't see that i have logged in so i cant use it.
![Screenshot (112)](https://user-images.githubusercontent.com/62519329/116828407-c13b3f00-ab9e-11eb-93da-640aaf8b8a35.png)

**Comment by leeroybrun** [comment]
Thank you for your report.

I just pushed a new version of the extension to be reviewed by Google (v0.4.8), which should fix this issue.

Please be aware that Shazam seems to be changing a lot of things and from what I understand we may not be able to fetch the Shazam tags anymore in the near future. So enjoy it while it lasts. :-)

Have a great day!
