### ISSUE TITLE
Even after v0.4.8, Shazify doesn't recognize Shazam login

### ISSUE THREAD

**Issue by conformist1** [leeroybrun/chrome-shazify#34]
Hi there, this is following on #27 which was closed, saying that v0.4.8 would fix this issue but it hasn't fixed it for me. I'm on Chrome  90.0.4430.212 and when I try to click the icon again after logging in, it doesn't refresh itself.

![image](https://user-images.githubusercontent.com/46271586/118352107-7f9e8280-b514-11eb-9da9-469bcbeb475a.png)

**Comment by leeroybrun** [comment]
Can you please try to click again on the "Open the login page" button in Shazify, even if you are already logged in?

**Comment by conformist1** [comment]
Yes, same result. Just reloads the same logged-in page.

Lolo Haha (he/him)
Counselor, equity consultant, conflict mediator, and social justice theatre director based in Portland, Oregon
lolohaha.us

In my path I find myself regularly wanting answers to some of the most fundamental questions of life: Why are we here? Why is there injustice in the world? As I struggle to find conclusive answers, I find solace in the following quote:
"...I would like to beg you, as well as I can, to have patience with everything unresolved in your heart and to try to love the questions themselves as if they were locked rooms or books written in a very foreign language. Don't search for the answers, which could not be given to you now, because you would not be able to live them. And the point is to live everything. Live the questions now. Perhaps then, someday far in the future, you will gradually, without even noticing it, live your way into the answer."
 - Rainer Maria Rilke, from Letters to a Young Poet (1903)

**Comment by leeroybrun** [comment]
Sorry for the late reply...

Are you connected with Facebook on Shazam?
Shazify only works if you are connected with Facebook on the Shazam app on your phone and then you must connect with Facebook on the Shazam website too.

Also, please check that in the extension's settings it has access to the Shazam and Spotify websites :
![Capture d’écran 2021-07-14 à 14 47 18](https://user-images.githubusercontent.com/1729528/125624581-45fc057c-2e0b-49f3-8ee4-6c9ff8068b65.png)

**Comment by leeroybrun** [comment]
Unfortunately it seems to be a deprecated feature (https://www.shazam.com/en/login/app/fb/myshazam).
So I guess it only works if you already were connected on the Shazam app with Facebook before they changed it.
Since then, Shazam has changed the way they store the songs you Shazamed, they now seems to be stored on iCloud.
I don't know how this works on Android though.

I don't know if we will be able to still retrieve them unfortunately...
I would need to have a deeper look and dive in the new inner workings of the Shazam website to find out.

Until then, Shazify will only work with older Shazam accounts using Facebook login unfortunately.

**Comment by conformist1** [comment]
No worries, seems to be working great even without it!

**Comment by leeroybrun** [comment]
Just to let you know that I published a new version (v0.5.0) which should work with the "new" Shazam syncs (iCloud and Google).

I hope that maybe this new version will work for you!
It is under review by Google, so it may take a while to get published.

Also, please note that Shazam plan to remove the "My Library" from their website, so when that happens we may not be able to get the tags from a Chrome extension anymore, and Shazify may stop working altogether. More info : https://github.com/leeroybrun/chrome-shazify/issues/36

**Comment by conformist1** [comment]
Thank you!

Lolo Haha (he/him)
Counselor, equity consultant, conflict mediator, and social justice theatre director based in Portland, Oregon
lolohaha.us

In my path I find myself regularly wanting answers to some of the most fundamental questions of life: Why are we here? Why is there injustice in the world? As I struggle to find conclusive answers, I find solace in the following quote:
"...I would like to beg you, as well as I can, to have patience with everything unresolved in your heart and to try to love the questions themselves as if they were locked rooms or books written in a very foreign language. Don't search for the answers, which could not be given to you now, because you would not be able to live them. And the point is to live everything. Live the questions now. Perhaps then, someday far in the future, you will gradually, without even noticing it, live your way into the answer."
 - Rainer Maria Rilke, from Letters to a Young Poet (1903)
