### ISSUE TITLE
Only three shazam tags were added

### ISSUE THREAD

**Issue by nopersonalive** [leeroybrun/chrome-shazify#8]
Hello. 

I have 20+ shazam tags. 

I syncronized everything. The playlist was created, but it remained empty for about two hours. 

Next, I tried to correct the search query of one of the songs with the orange X. After changing the query for three songs, I checked the playlist. The three songs I had changed were added, but none else. 

What Information can I give you to reproduce the issue?

Im on chrome 38.0.2125.122. and the plugin version is 0.1.4.

Thank you.

**Comment by leeroybrun** [comment]
Fine, I'm happy to read that all is working as expected !
